export const JAVASCRIPT = {
    basic: {
      questions: [
        {
          id: 1,
          question: 'What is JavaScript?',
          options: [
            'A programming language',
            'A markup language',
            'A database',
            'A stylesheet language',
          ],
          answer: 'A programming language',
          completed: false,
          userSelected: '',
        },
        {
          id: 2,
          question: 'Which company developed JavaScript?',
          options: ['Netscape', 'Microsoft', 'Google', 'Apple'],
          answer: 'Netscape',
          completed: false,
          userSelected: '',
        },
        {
          id: 3,
          question: 'Which symbol is used for comments in JavaScript?',
          options: ['//', '/* */', '<!-- -->', '#'],
          answer: '//',
          completed: false,
          userSelected: '',
        },
        {
          id: 4,
          question: 'How do you create a function in JavaScript?',
          options: [
            'function myFunction()',
            'function:myFunction()',
            'function = myFunction()',
            'myFunction function()',
          ],
          answer: 'function myFunction()',
          completed: false,
          userSelected: '',
        },
        {
          id: 5,
          question: 'How do you call a function named "myFunction"?',
          options: [
            'myFunction()',
            'call myFunction()',
            'call function myFunction()',
            'call myFunction',
          ],
          answer: 'myFunction()',
          completed: false,
          userSelected: '',
        },
        {
          id: 6,
          question: 'How to write an IF statement in JavaScript?',
          options: [
            'if (i == 5)',
            'if i = 5',
            'if i == 5 then',
            'if i = 5 then',
          ],
          answer: 'if (i == 5)',
          completed: false,
          userSelected: '',
        },
        {
          id: 7,
          question: 'How does a WHILE loop start?',
          options: [
            'while (i <= 10)',
            'while i = 1 to 10',
            'while (i <= 10; i++)',
            'while (i = 0; i <= 10)',
          ],
          answer: 'while (i <= 10)',
          completed: false,
          userSelected: '',
        },
        {
          id: 8,
          question: 'How can you add a comment in JavaScript?',
          options: [
            '// This is a comment',
            '\'This is a comment',
            '<!-- This is a comment -->',
            '** This is a comment',
          ],
          answer: '// This is a comment',
          completed: false,
          userSelected: '',
        },
        {
          id: 9,
          question: 'Which event occurs when the user clicks on an HTML element?',
          options: ['onclick', 'onchange', 'onmouseclick', 'onmouseover'],
          answer: 'onclick',
          completed: false,
          userSelected: '',
        },
        {
          id: 10,
          question: 'What is the correct way to write a JavaScript array?',
          options: [
            'var colors = ["red", "green", "blue"]',
            'var colors = "red", "green", "blue"',
            'var colors = (1:"red", 2:"green", 3:"blue")',
            'var colors = 1 = ("red"), 2 = ("green"), 3 = ("blue")',
          ],
          answer: 'var colors = ["red", "green", "blue"]',
          completed: false,
          userSelected: '',
        },
      ],
    },
    intermidiate: {},
    advance: {},
  };
  