export const REACT = {
  basic: {
    questions: [
      {
        id: 1,
        question: 'What is React?',
        options: [
          'A JavaScript library for building user interfaces',
          'A framework for building mobile applications',
          'A server-side scripting language',
          'A database management system',
        ],
        answer: 'A JavaScript library for building user interfaces',
        completed: false,
        userSelected: '',
      },
      {
        id: 2,
        question: 'Who developed React?',
        options: ['Google', 'Facebook', 'Microsoft', 'Twitter'],
        answer: 'Facebook',
        completed: false,
        userSelected: '',
      },
      {
        id: 3,
        question: 'What is a component in React?',
        options: [
          'A function or class that optionally accepts input and returns a React element',
          'A database table',
          'A function that takes a callback as an argument',
          'A built-in JavaScript object',
        ],
        answer:
          'A function or class that optionally accepts input and returns a React element',
        completed: false,
        userSelected: '',
      },
      {
        id: 4,
        question: 'What is JSX?',
        options: [
          'A syntax extension for JavaScript that looks similar to XML or HTML',
          'A type of JavaScript variable',
          'A built-in JavaScript function',
          'A database query language',
        ],
        answer:
          'A syntax extension for JavaScript that looks similar to XML or HTML',
        completed: false,
        userSelected: '',
      },
      {
        id: 5,
        question: 'What is the virtual DOM?',
        options: [
          'An in-memory representation of the real DOM elements generated by React components before any changes are made to the page',
          'A copy of the real DOM that gets updated in real-time',
          'A database for storing DOM elements',
          'A server-side rendering technique',
        ],
        answer:
          'An in-memory representation of the real DOM elements generated by React components before any changes are made to the page',
        completed: false,
        userSelected: '',
      },
      {
        id: 6,
        question: 'What is a state in React?',
        options: [
          'A built-in object used to contain data or information about the component',
          'A function that gets executed when the component renders',
          'A method to update the component layout',
          'A way to pass data to components',
        ],
        answer:
          'A built-in object used to contain data or information about the component',
        completed: false,
        userSelected: '',
      },
      {
        id: 7,
        question: 'How do you create a React component?',
        options: [
          'By defining a JavaScript function or class that returns a React element',
          'By creating a new HTML file',
          'By initializing a new database',
          'By defining a CSS style sheet',
        ],
        answer:
          'By defining a JavaScript function or class that returns a React element',
        completed: false,
        userSelected: '',
      },
      {
        id: 8,
        question: 'What are props in React?',
        options: [
          'Inputs to a React component that allow data to be passed from one component to another',
          'Global variables in React',
          'Methods to update the state',
          'Built-in React functions',
        ],
        answer:
          'Inputs to a React component that allow data to be passed from one component to another',
        completed: false,
        userSelected: '',
      },
      {
        id: 9,
        question: 'What is the purpose of a key in React lists?',
        options: [
          'To give each element in the list a stable identity',
          'To set a unique class name for each element',
          'To generate a unique ID for each element',
          'To trigger re-rendering of the list items',
        ],
        answer: 'To give each element in the list a stable identity',
        completed: false,
        userSelected: '',
      },
      {
        id: 10,
        question: 'What is a React fragment?',
        options: [
          'A way to group a list of children without adding extra nodes to the DOM',
          'A part of the React virtual DOM',
          'A method to handle state changes',
          'A component lifecycle method',
        ],
        answer:
          'A way to group a list of children without adding extra nodes to the DOM',
        completed: false,
        userSelected: '',
      },
    ],
  },
  intermidiate: {},
  advance: {},
};
