export const CSS = {
    basic: {
      questions: [
        {
          id: 1,
          question: 'What does CSS stand for?',
          options: [
            'Cascading Style Sheets',
            'Creative Style Sheets',
            'Computer Style Sheets',
            'Colorful Style Sheets',
          ],
          answer: 'Cascading Style Sheets',
          completed: false,
          userSelected: '',
        },
        {
          id: 2,
          question: 'Which HTML attribute is used to define inline styles?',
          options: ['style', 'class', 'font', 'styles'],
          answer: 'style',
          completed: false,
          userSelected: '',
        },
        {
          id: 3,
          question: 'Which is the correct CSS syntax?',
          options: [
            'body {color: black;}',
            '{body;color:black;}',
            'body:color=black;',
            '{body:color=black;}',
          ],
          answer: 'body {color: black;}',
          completed: false,
          userSelected: '',
        },
        {
          id: 4,
          question: 'How do you insert a comment in a CSS file?',
          options: [
            '/* this is a comment */',
            '// this is a comment',
            "' this is a comment",
            '<!-- this is a comment -->',
          ],
          answer: '/* this is a comment */',
          completed: false,
          userSelected: '',
        },
        {
          id: 5,
          question: 'Which property is used to change the background color?',
          options: ['background-color', 'color', 'bgcolor', 'background'],
          answer: 'background-color',
          completed: false,
          userSelected: '',
        },
        {
          id: 6,
          question: 'How do you add a background color for all <h1> elements?',
          options: [
            'h1 {background-color:#FFFFFF;}',
            'all.h1 {background-color:#FFFFFF;}',
            'h1.all {background-color:#FFFFFF;}',
            'h1.all {bgcolor:#FFFFFF;}',
          ],
          answer: 'h1 {background-color:#FFFFFF;}',
          completed: false,
          userSelected: '',
        },
        {
          id: 7,
          question: 'Which CSS property is used to change the text color of an element?',
          options: ['color', 'text-color', 'fgcolor', 'font-color'],
          answer: 'color',
          completed: false,
          userSelected: '',
        },
        {
          id: 8,
          question: 'Which CSS property controls the text size?',
          options: ['font-size', 'text-size', 'font-style', 'text-style'],
          answer: 'font-size',
          completed: false,
          userSelected: '',
        },
        {
          id: 9,
          question: 'How do you display hyperlinks without an underline?',
          options: [
            'a {text-decoration:none;}',
            'a {underline:none;}',
            'a {text-decoration:no-underline;}',
            'a {decoration:no-underline;}',
          ],
          answer: 'a {text-decoration:none;}',
          completed: false,
          userSelected: '',
        },
        {
          id: 10,
          question: 'Which property is used to change the font of an element?',
          options: ['font-family', 'font-weight', 'font-style', 'font-size'],
          answer: 'font-family',
          completed: false,
          userSelected: '',
        },
      ],
    },
    intermidiate: {},
    advance: {},
  };
  